# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'cupertino_icons'
  pod 'geolocator'
  pod 'GoogleMaps'
  pod 'weather'
  pod 'intl'
  pod 'google_fonts'
  pod 'camera'
  pod 'path_provider'
  pod 'geocoding'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
