# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'GoogleMaps'

  # Add pods for other dependencies
  pod 'geolocator', '~> 11.0.0'
  pod 'camera', '~> 0.10.5'
  pod 'path_provider', '~> 2.1.3'
  pod 'geocoding', '~> 3.0.0'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
